rootProject.name = "springinaction5"
include("tacocloud-api")
include("tacocloud-data")
include("tacocloud-domain")
include("tacocloud-security")
include("tacocloud-web")
include("tacos")
include("tacocloud-ui")
include("tacocloud-restclient")
include("tacocloud-messaging-rabbitmq")
include("tacocloud-kitchen")
include("tacocloud-messaging-kafka")
include("tacocloud-email")
include("reactor")
