server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: tacoweb
    password: l3tm31n

  kafka:
    consumer:
      group-id: tacocloud-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"