spring:
  data:
    rest:
      base-path: /api
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  rabbitmq:
    host: localhost
    port: 5672
    username: tacoweb
    password: l3tm31n
  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: tacocloud.orders.topic
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

taco:
  orders:
    page-size: 10

logging:
  level:
    tacos: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/tacocloud
    username: tacouser
    password: tacopassword
  rabbitmq:
    host: localhost
    port: 5673
    username: tacoweb
    password: l3tm31n

logging:
  level:
    tacos: WARN

